<body style="background-color:#dae4e8;">

Return [Home](https://jakobaggers.github.io/mywebsite/)

## News Story

Below is a news story I wrote for Advanced News Reporting while covering the WMATA/D.C. Public Transportation Beat.

Jakob Aggers

Professor Thompson

Advanced News Reporting

12 December 2022

\

Metro Transit Police Department (MTPD) officials arrested a 16-year-old-boy on Friday as the primary suspect in a shooting at the Benning Road station, WMATA officials said. Three people were injured in the shooting that occurred Thursday morning.

The suspect was arrested in Northwest DC and is being charged with attempted second degree murder and carrying a firearm without a license, according to WMATA officials. 

The quick investigation and arrest were made possible by surveillance and recently increased police presence, Metro General Manager Randy Clarke said in a press release.

"Metro has an extensive network of surveillance cameras that allow us to quickly identify perpetrators of violence and bring them to justice," Clarke said. "MTPD has dramatically increased its presence on rail and bus in the past several months to keep customers safe." 

The shooting Thursday morning comes hours after a separate altercation that happened at the Metro Center station on Wednesday evening at 6:39 p.m., during which an off-duty FBI agent shot and killed a civilian, according to an MPD public incident report. 

Troy Bullock, the 28-year-old man identified as the suspect, pushed the unnamed FBI agent over a concrete railing and both men fell eight feet onto a maintenance walkway. The FBI agent then fired at Bullock with his issued service pistol, according to the incident report.

As seen in publicly released surveillance footage from both incidents, mobs of people waiting at the platform stampeded towards the exits. 

Gabriel Molini, a 21-year-old student at The Catholic University of America, was on the lower level platform in Metro Center when Bullock was killed on Wednesday evening.

"I heard the shots ring out, and I was in shock. I saw everybody running, and I thought somebody was shooting up the station," Molini said in an interview. "I stayed with the crowd and jumped over the meter, but some people were even trying to swipe out. It was a total stampede." 

Those present during the recent shootings will likely cause a rise in discomfort among riders, Molini said. 

"I've never felt truly safe on the Metro," Molini said. "I use it out of necessity, to be honest. It's the cheapest way to get around the city. So, I'll continue to use it, but it won't be because I feel comfortable."\

Some Metro employees no longer feel comfortable talking about safety in Metro facilities for fear of repercussions. 

"Things have been real bad around here man, and I'm not allowed to tell you my honest opinion," said Foggy Bottom Station Manager T. Jeter in an interview. "I don't want to get in trouble for saying something I shouldn't say, and I don't want to shoot you no b.s."

The two shootings in Metro rail stations signify a rapid increase in violent crime and decrease in safety at Metro stops.\

These incidents come just days after MTPD released their monthly crime report on Dec. 6, 2022. 

Instances of violent crime have increased since 2021, according to the report. There have been 178 instances of aggravated assault in Metro facilities in 2022, opposed to 162 in 2021. The number of cases of rape have doubled in 2022. 

The total number of violent crimes recorded in 2022 was 857, compared to 641 in 2021. The total number of nonviolent crimes, labeled as "Part 2 Crimes," rose from 2,905 in 2021 to 3,262 in 2022. 

Despite the number of crimes increasing dramatically in 2022, the number of arrests has not increased at the same rate. MTPD made only 13 more arrests in 2022 than in 2021. The number of citations issued by MTPD officers has decreased from 684 in 2021 to 653 in 2022.\

Some frequent riders say that the Metro has become much more dangerous after the COVID-19 pandemic. 

"Prior to the pandemic, I felt okay riding the Metro alone when votes went long, sometimes getting home after 11pm, but now, I would rather spend the \$20 to Uber," said Capitol Hill staffer Stacey Peuplie. "The lack of crime enforcement on the metro makes me nervous to ride alone when it gets dark, which defeats the purpose of public transportation, if the public can't use it safely."\

Each of the nonviolent and violent crimes are connected, said frequent Metro rider Alexandra Hudepohl. When MTPD chooses not to enforce misdemeanors, many riders begin to think that the Metro is a free for all.

"When they don't enforce small crimes, like fare evasion, people realize that there's no consequence for their actions because they get away with legal offenses repeatedly," Hudepohl said in an interview. "Then, it escalates, and eventually someone brings a gun because they don't think anyone is going to stop them."\

The rise in crime on Metro services is a reflection of a rise in crime in the city as a whole, Station Manager Ed Knight said in an interview. In order to reduce crime in the Metro system, the city needs to reduce crime overall.\

"Unfortunately we're not exempt \[from violent crimes\]," Knight said. "If it happens in the streets, it's gonna happen here. The same folks come to public transportation, and there's nothing we can do to get away from it."
